name: pyatsa
channels:
  - conda-forge
dependencies:
  # pyatsa requirements
  - numpy>=1.8
  - scipy>=1.3.0
  - scikit-image>=0.15
  - statsmodels=0.10.0
  - scikit-learn>=0.21.2
  - xarray>=0.12.3
  - dask>=2.1.0
  - ipykernel
  - flake8
  - pip:
    - flit # used to publish to pypi and install pyatsa locally for development
    - rasterio>=1.0.7
    - porder
    - rioxarray

